# Generated by Django 4.2.3 on 2023-11-17 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0004_category_is_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='offerprice',
        ),
    ]
