# Generated by Django 4.2.3 on 2023-11-23 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0008_colorvariant_sizevariant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sizevariant',
            name='real_price',
        ),
    ]
