# Generated by Django 4.2.3 on 2023-11-24 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0009_remove_sizevariant_real_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image_stocks/')),
                ('color_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminside.colorvariant')),
                ('size_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminside.sizevariant')),
            ],
        ),
    ]
