# Generated by Django 4.2.3 on 2023-11-29 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0010_imagestock'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagestock',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminside.product'),
        ),
    ]
