# Generated by Django 4.2.3 on 2023-12-06 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0011_imagestock_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorvariant',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sizevariant',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
