# Generated by Django 4.2.3 on 2023-11-29 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_remove_account_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='referral_id',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.CharField(default=False, max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='currentuser',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='homeaddress',
            field=models.TextField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pincode',
            field=models.IntegerField(default=False),
        ),
    ]
