# Generated by Django 4.2.3 on 2023-12-04 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_remove_userprofile_otp_alter_userprofile_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='is_default',
            field=models.BooleanField(default=True),
        ),
    ]
