# Generated by Django 4.2.3 on 2023-12-04 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_orderproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='final_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
