# Generated by Django 4.2.3 on 2023-12-05 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_remove_order_user_order_user_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='user',
            new_name='user_profile',
        ),
    ]
