# Generated by Django 4.2.7 on 2023-12-09 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0012_alter_userprofile_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_code', models.CharField(max_length=20, unique=True)),
                ('expiration_date', models.DateField()),
                ('discount_price', models.IntegerField(default=100)),
                ('minimum_purchase_amount', models.IntegerField(default=500)),
            ],
        ),
    ]
