# Generated by Django 4.2.3 on 2023-12-09 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0013_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='discount_price',
            field=models.IntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='minimum_purchase_amount',
            field=models.IntegerField(default=False),
        ),
    ]
